In [11]:
# import os
# import sys
import pandas as pd
# from dotenv import load_dotenv
# from pymongo import MongoClient

In [12]:
# load_dotenv()
# mongodb_uri = os.getenv('MONGODB_URI')
uri = "mongodb+srv://rkhridoyinfo:rkhridoyinfo@cluster0.siodkrr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

In [13]:
def load_mongoDB():
    try:
        clint = MongoClient(uri)
        db = clint['mobileDB']
        collection = db['mobileDataset']
        df = pd.DataFrame(list(collection.find()))
        return df
    except Exception as e:
        print(e)

In [14]:
data = load_mongoDB()
data.head()

,_id,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,6832c7c91418a0502c63be98,842,0,2.2,0,1,0,7,0.6,188,...,20,756,2549,9,7,19,0,0,1,1
1,6832c7c91418a0502c63be99,1021,1,0.5,1,0,1,53,0.7,136,...,905,1988,2631,17,3,7,1,1,0,2
2,6832c7c91418a0502c63be9a,563,1,0.5,1,2,1,41,0.9,145,...,1263,1716,2603,11,2,9,1,1,0,2
3,6832c7c91418a0502c63be9b,615,1,2.5,0,0,0,10,0.8,131,...,1216,1786,2769,16,8,11,1,0,0,2
4,6832c7c91418a0502c63be9c,1821,1,1.2,0,13,1,44,0.6,141,...,1208,1212,1411,8,2,15,1,1,0,1

In [15]:
import os
import pandas as pd
from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv()
mongodb_uri = os.getenv('mongodb_uri')

def load_mongoDB():
    try:
        clint = MongoClient(mongodb_uri)
        db = clint['mobileDB']
        collection = db['mobileDataset']
        df = pd.DataFrame(list(collection.find()))
        return df
    except Exception as e:
        print(e)
        
data = load_mongoDB()
print(data.head())

                        _id  battery_power  blue  clock_speed  dual_sim  fc  \
0  6832c7c91418a0502c63be98            842     0          2.2         0   1
1  6832c7c91418a0502c63be99           1021     1          0.5         1   0
2  6832c7c91418a0502c63be9a            563     1          0.5         1   2
3  6832c7c91418a0502c63be9b            615     1          2.5         0   0
4  6832c7c91418a0502c63be9c           1821     1          1.2         0  13

   four_g  int_memory  m_dep  mobile_wt  ...  px_height  px_width   ram  sc_h  \
0       0           7    0.6        188  ...         20       756  2549     9
1       1          53    0.7        136  ...        905      1988  2631    17
2       1          41    0.9        145  ...       1263      1716  2603    11
3       0          10    0.8        131  ...       1216      1786  2769    16
4       1          44    0.6        141  ...       1208      1212  1411     8

   sc_w  talk_time  three_g  touch_screen  wifi  price_range
0     7         19        0             0     1            1
1     3          7        1             1     0            2
2     2          9        1             1     0            2
3     8         11        1             0     0            2
4     2         15        1             1     0            1

[5 rows x 22 columns]

In [17]:

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://rkhridoyinfo:dvcpassword@dvc.xyf41mq.mongodb.net/?retryWrites=true&w=majority&appName=dvc"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!